import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from '@rstest/core';

const SNAPSHOT_PATH = 'published/current/fpf-index/snapshot.json';
const WORKFLOW_DIR = '.github/workflows';

/**
 * published/current/fpf-index/snapshot.json is a 95MB build product. It was
 * Git LFS-tracked from 2026-07-05 (PR #236) until the LFS budget 403 broke
 * `actions/checkout` in every workflow that set `lfs: true` — 34 consecutive
 * sync failures, a dead CI, and an unclonable repo between 2026-07-16 and
 * 2026-07-28. It is now regenerated by `bun run ensure:snapshot`.
 *
 * A previous agent added `lfs: true` to fpf-content-quality.yml deliberately,
 * so "nobody would do that again" is not a control. These assertions are.
 */
describe('published snapshot stays out of git', () => {
  it('has no .gitattributes (the only entry was the LFS rule)', () => {
    expect(existsSync('.gitattributes')).toBe(false);
  });

  it('does not track the snapshot', () => {
    const result = spawnSync('git', ['ls-files', '--error-unmatch', SNAPSHOT_PATH], {
      encoding: 'utf8',
    });
    expect(result.status).not.toBe(0);
  });

  it('ignores the exact snapshot path', () => {
    const gitignore = readFileSync('.gitignore', 'utf8');
    expect(gitignore.split('\n')).toContain(SNAPSHOT_PATH);
  });

  it('has no lfs: in any workflow', () => {
    const offenders = readdirSync(WORKFLOW_DIR)
      .filter((name) => name.endsWith('.yml') || name.endsWith('.yaml'))
      .filter((name) => readFileSync(join(WORKFLOW_DIR, name), 'utf8').includes('lfs:'));
    expect(offenders).toEqual([]);
  });

  it('never stages the snapshot in the sync worker or the pre-push hook', () => {
    // The path may still be *read* — sync-fpf.yml greps it to assert the
    // per-section blame stamps survived publish:current. What must never come
    // back is staging it: a `git add` continuation line, or a bare entry in
    // create-pull-request's `add-paths:` list.
    for (const file of ['.github/workflows/sync-fpf.yml', 'scripts/hooks/pre-push.sh']) {
      const staged = readFileSync(file, 'utf8')
        .split('\n')
        .filter((line) => line.includes(SNAPSHOT_PATH))
        .filter((line) => {
          const trimmed = line.trim().replace(/\s*\\$/u, '');
          return trimmed === SNAPSHOT_PATH || /\bgit add\b/u.test(line);
        });
      expect({ file, staged }).toEqual({ file, staged: [] });
    }
  });
});
