import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { describe, expect, it } from '@rstest/core';

describe('sync FPF publication workflow', () => {
  it('keeps published surfaces current from Anatoly Levenchuk FPF through dispatch and monitor handoff', async () => {
    const workflow = await readFile(
      resolve(process.cwd(), '.github/workflows/sync-fpf.yml'),
      'utf8',
    );

    expect(workflow).toContain('repository_dispatch:');
    expect(workflow).toContain('types: [fpf-origin-updated, fpf-sync-updated]');
    expect(workflow).not.toContain('schedule:');
    expect(workflow).toContain('workflow_dispatch:');
    expect(workflow).toContain('fpf-sync-monitor.yml');
    expect(workflow).toContain('ailev/FPF');
    expect(workflow).not.toContain('venikman');
  });

  it('passes one resolved upstream ref to download and publish', async () => {
    const workflow = await readFile(
      resolve(process.cwd(), '.github/workflows/sync-fpf.yml'),
      'utf8',
    );

    expect(workflow).toContain('id: upstream');
    expect(workflow).toContain(
      'FPF_UPSTREAM_REF: ${{ steps.upstream.outputs.ref }}',
    );
    expect(workflow).toContain(
      'FPF_UPSTREAM_SPEC_URL: ${{ steps.upstream.outputs.spec_url }}',
    );
    expect(workflow).toContain('spec_url requires client_payload.sha/after/ref/branch');
  });

  it('checks the manually triggered CI run by head SHA before auto-merge', async () => {
    const workflow = await readFile(
      resolve(process.cwd(), '.github/workflows/sync-fpf.yml'),
      'utf8',
    );

    expect(workflow).toContain('gh workflow run ci.yml --ref "$SYNC_BRANCH"');
    expect(workflow).toContain('PR_HEAD_SHA=$(gh pr view "$PR_NUMBER" --json headRefOid');
    expect(workflow).toContain('--workflow ci.yml');
    expect(workflow).toContain('--branch "chore/sync-fpf-${{ steps.detect.outputs.short_ref }}"');
    expect(workflow).toContain('select(.headSha == \\"$PR_HEAD_SHA\\")');
    expect(workflow).toContain('CI_CONCLUSION');
    expect(workflow).toContain(
      'REQUIRED_CHECK_NAMES=\'["Build (docs + MCP + Vercel dry-runs)","Vercel","Playwright on Vercel preview"]\'',
    );
    expect(workflow).toContain('VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}');
    expect(workflow).toContain('bun run deploy:prod');
    expect(workflow).toContain('Repair production deploy when published/current is already current');
    expect(workflow).toContain(
      "if: steps.detect.outputs.changed == 'false' && github.ref == 'refs/heads/main'",
    );
    expect(workflow).toContain('FPF_VERCEL_SCOPE: team_CnO1I5xd2OS0lzbbc4RkW7Ym');
    expect(workflow).toContain('SYNC_OK=false');
    expect(workflow).toContain('CONTENT_OK=false');
    expect(workflow).toContain('if [ "$SYNC_OK" = "true" ] && [ "$CONTENT_OK" = "true" ]; then');
    expect(workflow).toContain('Production monitor failed while published/current has no upstream diff');
    expect(workflow).toContain('bun run monitor:content -- --mode live --format markdown --fail-on-breach');
    expect(workflow).toContain('test -f .vercel/output/static/fpf-publication-manifest.json');
  });

  it('monitors production drift and triggers sync without user intervention', async () => {
    const workflow = await readFile(
      resolve(process.cwd(), '.github/workflows/fpf-sync-monitor.yml'),
      'utf8',
    );

    expect(workflow).toContain("- cron: '17 * * * *'");
    expect(workflow).toContain(
      'FPF_SYNC_MONITOR_STATUS_URL: https://mcp.fpf.sh/api/fpf/status',
    );
    expect(workflow).toContain('bun run monitor:sync -- --format markdown');
    expect(workflow).toContain('Check for existing target sync PR');
    expect(workflow).toContain('--head "$TARGET_BRANCH"');
    expect(workflow).toContain('headRepositoryOwner.login == $owner');
    expect(workflow).toContain('.author.login == "app/github-actions"');
    expect(workflow).toContain('Generated by `.github/workflows/sync-fpf.yml`.');
    expect(workflow).toContain('Check for active sync worker');
    expect(workflow).toContain('--workflow sync-fpf.yml');
    expect(workflow).toContain('.status == "queued"');
    expect(workflow).toContain('.status == "in_progress"');
    expect(workflow).toContain('gh workflow run sync-fpf.yml --ref main');
    expect(workflow).toContain('steps.monitor.outputs.needs_sync');
    expect(workflow).toContain("steps.active_sync_worker.outputs.active != 'true'");
    expect(workflow).not.toContain("steps.open_sync_pr.outputs.target_exists != 'true'");
    expect(workflow).toContain('steps.monitor.outputs.breached');
  });

  it('closes superseded sync PRs before opening the current publication PR', async () => {
    const workflow = await readFile(
      resolve(process.cwd(), '.github/workflows/sync-fpf.yml'),
      'utf8',
    );

    expect(workflow).toContain('Close superseded sync PRs');
    expect(workflow).toContain("if: steps.detect.outputs.changed == 'true'");
    expect(workflow).toContain('startswith("chore/sync-fpf-")');
    expect(workflow).toContain('headRepositoryOwner.login == $owner');
    expect(workflow).toContain('.author.login == "app/github-actions"');
    expect(workflow).toContain('Generated by `.github/workflows/sync-fpf.yml`.');
    expect(workflow).toContain('Closing as superseded by the current publication sync target');
    expect(workflow).not.toContain('already matches the resolved upstream ref; this sync PR is stale.');
    expect(workflow).toContain('gh pr close "$number" --comment "$COMMENT"');
  });
});
